export const experiences = [
  {
    title: "CIPTA IT Developer: Mobile Developer",
    company: "CIMB Niaga · Contract",
    date: "Oct 2024 - Present · 10 mos",
    location: "Tangerang, Banten, Indonesia · On-site",
    points: [
      "Worked as a Mobile Developer in the Corporate Internet Banking division, assigned to the NGB (New Generation Bizchannel) Project Team.",
      "Collaborated with external vendors to develop and enhance the OCTO Biz Mobile application for corporate users using React Native.",
      "Participated in daily Agile ceremonies (sprint planning, daily standups, retrospectives) within a cross-functional team of 20+ members.",
      "Consistently completed all backlog items in every sprint on time, ensuring seamless integration with backend services and APIs.",
      "Identified and resolved 30+ issues and additional requests during the testing process.",
    ],
    side: "left",
  },
  {
    title: "Mobile Developer",
    company: "Mandaya Royal Hospital Group",
    date: "Nov 2021 - Nov 2024",
    location: "Jakarta",
    points: [
      "Contributed to the development of a hospital service booking app...",
      "Built a digital queue system for mobile users...",
      "Developed an Android TV application...",
      "Performed ongoing bug fixes...",
    ],
    side: "right",
  },
  {
    title: "Mobile Developer",
    company: "Mandaya Royal Hospital Group",
    date: "Nov 2021 - Nov 2024",
    location: "Jakarta",
    points: [
      "Contributed to the development of a hospital service booking app...",
      "Built a digital queue system for mobile users...",
      "Developed an Android TV application...",
      "Performed ongoing bug fixes...",
    ],
    side: "left",
  },
  {
    title: "Mobile Developer",
    company: "Mandaya Royal Hospital Group",
    date: "Nov 2021 - Nov 2024",
    location: "Jakarta",
    points: [
      "Contributed to the development of a hospital service booking app...",
      "Built a digital queue system for mobile users...",
      "Developed an Android TV application...",
      "Performed ongoing bug fixes...",
    ],
    side: "right",
  },
  {
    title: "Mobile Developer",
    company: "Mandaya Royal Hospital Group",
    date: "Nov 2021 - Nov 2024",
    location: "Jakarta",
    points: [
      "Contributed to the development of a hospital service booking app...",
      "Built a digital queue system for mobile users...",
      "Developed an Android TV application...",
      "Performed ongoing bug fixes...",
    ],
    side: "left",
  },
];
