import ImageCompanyCIMBNiaga from "../../../assets/images/iv_company_cimb_niaga.png";
import ImageCompanyPhinconAcademy from "../../../assets/images/iv_company_phincon_academy.jpeg";
import ImageCompanyIDXPartners from "../../../assets/images/iv_company_idx_partners.png";
import ImageCompanyAndroidUPNVJ from "../../../assets/images/iv_company_android_upnvj.png";
import ImageCompanyBangkit from "../../../assets/images/iv_company_bangkit.jpeg";
import ImageCompanySMFIKUPNVJ from "../../../assets/images/iv_company_smfik_upnvj.png";
import ImageCompanyKemenkumham from "../../../assets/images/iv_company_kemenkumham.png";
import ImageCompanyJujitsuBulungan from "../../../assets/images/iv_company_jujitsu_bulungan.png";

export const experiences = [
  {
    title: "CIPTA IT Developer: Mobile Developer",
    company: "CIMB Niaga · Contract",
    companyImage: ImageCompanyCIMBNiaga,
    date: "Oct 2024 - Present · 10 mos",
    location: "Tangerang, Banten, Indonesia · On-site",
    points: [
      "Worked as a Mobile Developer in the Corporate Internet Banking division, assigned to the NGB (New Generation Bizchannel) Project Team.",
      "Collaborated with external vendors to develop and enhance the OCTO Biz Mobile application for corporate users using React Native.",
      "Participated in daily Agile ceremonies (sprint planning, daily standups, retrospectives) within a cross-functional team of 20+ members.",
      "Consistently completed all backlog items in every sprint on time, ensuring seamless integration with backend services and APIs.",
      "Identified and resolved 30+ issues and additional requests during the testing process.",
    ],
    skills: [
      "React Native",
      "JavaScript",
      "Redux.js",
      "React",
      "React Hooks",
      "Jira",
      "Bitbucket",
      "Confluence",
    ],
    side: "left",
  },
  {
    title: "Android Kotlin Bootcamp Scholarship Awardee",
    company: "Phincon Academy",
    companyImage: ImageCompanyPhinconAcademy,
    date: "Jun 2024 - Sep 2024",
    location: "South Jakarta, Jakarta, Indonesia · On-site",
    points: [
      'Achieved the "Achiever" predicate by consistently completing all Android Development tasks and soft skill sessions, including one task, three assignments, and a final project. Final grade: 87/100 (B), with 95% attendance.',
      "Completed a 12-week intensive program with 60 sessions focused on Android Development using Kotlin.",
      "Completed weekly exercises and assignments throughout the program duration to build Android development skills.",
      "Developed the カメラ屋 (Kameraya) app as a final project — an e-commerce platform specifically for selling cameras with an intuitive user interface and a wide selection of camera brands.",
    ],
    skills: [
      "Kotlin",
      "Android",
      "Android Development",
      "Android Studio",
      "UI/UX",
      "UI/UX Design",
    ],
    side: "right",
  },
  {
    title:
      "Project-Based Virtual Internship: Data Scientist ID/X Partners X Rakamin Academy",
    company: "ID/X Partners",
    companyImage: ImageCompanyIDXPartners,
    date: "Mar 2024 - Apr 2024",
    location: "Remote",
    points: [
      "Achieved qualified student status by diligently completing 9 Data Science assignments per week, which included company coaching videos, article reviews, and weekly assessments.",
      "Utilized tools and proficiencies commonly employed at ID/X Partners, including Big Data fundamentals, statistical analysis, SQL querying, R and Python programming, and machine learning techniques.",
      "Developed a comprehensive end-to-end Machine Learning model for Credit Risk Analysis tailored to Lending Companies, using 7 different algorithms.",
      "Achieved model performance with an average accuracy of 81%, where AdaBoost was the top-performing algorithm with an accuracy of 81.59%.",
    ],
    skills: [
      "Python",
      "Machine Learning",
      "Data Analytics",
      "Exploratory Data Analysis",
      "Data Science",
    ],
    side: "left",
  },
  {
    company: "KSM Android UPNVJ",
    companyImage: ImageCompanyAndroidUPNVJ,
    duration: "3 yrs 1 mo",
    date: "",
    title: "",
    points: [],
    skills: [],
    side: "right",
    subExperiences: [
      {
        title: "Leader",
        location: "South Jakarta, Jakarta, Indonesia · On-site",
        date: "Dec 2022 – Dec 2023",
        points: [
          "Led the organization, chaired meetings, and monitored performance to ensure optimal internal and external operations.",
          "Fostered effective communication within a 100-member organization, comprising 30 functionaries and 70 active members.",
          "Achieved 119.94% in the Organization Target Achievement Percentage.",
          "Spearheaded the creation of a comprehensive grand design consisting of 7 divisions and 32 programs (23 work programs and 9 non-work programs).",
          "Developed and implemented an Organizational Performance Indicator Tracker to monitor and evaluate performance.",
          "Ensured organizational transparency and accountability through public resources: Performance Tracker (https://bit.ly/TrackerPerformaKSMAnd-23) and Central Data (https://bit.ly/CentralDataKSMAndroid).",
        ],
        skills: ["Leadership", "Project Management"],
      },
      {
        title: "Member",
        location: "South Jakarta, Jakarta, Indonesia · On-site",
        date: "Dec 2020 – Dec 2023",
        points: [
          "Graduated from Kotlin Basic, UI/UX Basic, and Android Beginner classes.",
          "Built an e-commerce program, conducted user research for Baperin (a mental health app), and developed an app to display GitHub users as final projects.",
          "Participated in multiple committees including LPJ/STJ, Pemilu, Company Visit, and various workshops as staff or project officer.",
          "Mentored UI/UX and Kotlin Basic Study Clubs: taught 21 Kotlin mentees and 13 UI/UX mentees in 10 sessions each.",
          "Created and evaluated learning content, and assessed mentees' final projects.",
        ],
        skills: [
          "UI Design",
          "Android Development",
          "Mentoring",
          "Kotlin",
          "UX Research",
        ],
      },
      {
        title: "Head of Human Resources Division",
        location: "South Jakarta, Jakarta, Indonesia · On-site",
        date: "Dec 2021 – Dec 2022",
        points: [
          "Led the division, chaired division meetings, and monitored performance, ensuring optimal functioning both internally and externally.",
          "Spearheaded the development of a comprehensive Human Resource Division grand design and implemented a total of 12 impactful programs.",
          "Led the recruitment process with 200+ applicants.",
          "Provided monthly events to develop soft skills and enhance relationships among KSM Android members through discussions.",
          "Coordinated and successfully organized a Gathered Event with 60+ participants including alumni, functionaries, and active members.",
          "Supervised, maintained, and controlled the condition of KSM Android UPNVJ members through the Member Activity Monitoring HR System.",
        ],
        skills: [
          "Human Resources",
          "Leadership",
          "Recruitment",
          "Soft Skills Development",
        ],
      },
    ],
  },
  {
    title: "Mobile Development Cohort",
    company: "Bangkit Academy led by Google, Tokopedia, Gojek, & Traveloka",
    companyImage: ImageCompanyBangkit,
    date: "Feb 2023 - Jul 2023",
    location: "Indonesia · Remote",
    points: [
      "Graduated with Distinction from the Bangkit 2023 Mobile Development Cohort.",
      "Completed 11 asynchronous learning modules via Dicoding Academy (8 mandatory, 3 optional).",
      "Achieved 100% attendance in all program sessions, including Soft Skill, English, Career Development, and Instructor-Led Mobile Development Training.",
      "Collaborated in a team of 6 to develop the *TeMendaki* application — an open trip service enabling people to join mountain hiking tours with others as part of the capstone project.",
    ],
    skills: ["Kotlin", "Android Development"],
    side: "left",
  },
  {
    title: "Staff of Commission III for Supervision",
    company: "Senat Mahasiswa Fakultas Ilmu Komputer UPNVJ",
    companyImage: ImageCompanySMFIKUPNVJ,
    date: "Jan 2022 - Jan 2023",
    location: "Jakarta, Indonesia · On Site",
    points: [
      "Provided guidance, development, and supervision of BEMF-IK UPNVJ.",
      "Maintained strong coordination and relations with BEMF-IK UPNVJ.",
      "Reported supervision results to SMF-IK UPNVJ.",
      "Held accountability to the President of SMF-IK UPNVJ.",
    ],
    skills: ["Leadership", "Supervisory"],
    side: "left",
  },
  {
    title: "Fieldwork Practices",
    company: "Kementerian Hukum dan Hak Asasi Manusia Republik Indonesia",
    companyImage: ImageCompanyKemenkumham,
    date: "Aug 2022 - Sep 2022",
    location: "Jakarta, Indonesia · On Site",
    points: [
      "Studied the management structure and business processes of the Inspectorate General of the Ministry of Law and Human Rights (Kemenkumham).",
      "Created an Entity Relationship Diagram (ERD) for Disciplinary Punishment and Audit Board of Indonesia (BPK) Recommendations from the Surveillance System Database.",
      "Developed visualization queries for the data table containing BPK recommendations.",
    ],
    skills: ["SQL", "Database Management System (DBMS)"],
    side: "left",
  },
  {
    title: "Vice Chairman",
    company: "Ju-jitsu Bulungan",
    companyImage: ImageCompanyJujitsuBulungan,
    date: "Dec 2018 - Dec 2019",
    location: "Jakarta, Indonesia · On Site",
    points: [
      "Assisted the Chairman in leading the organization, including chairing meetings and monitoring overall performance to ensure smooth internal and external operations.",
      "Helped design and implement innovative programs to improve organizational quality and ensured proper execution.",
      "Led the organization of most club events, contributing to an engaging and active club environment.",
      "Managed practice schedules and timetables to maintain member consistency and participation.",
      "Built strong communication and collaboration with the school board, alumni, and student members to gather support and resources.",
      "Maintained effective communication and coordinated a club of around 60 active student members.",
    ],
    skills: ["Leadership", "Ju-jitsu Martial Arts"],
    side: "right",
  },
];
