import type { CertificationType } from "./CertificationType";
import ImageLogoDicoding from "../../../assets/images/iv_certification_dicoding.jpeg";
import ImageLogoBWA from "../../../assets/images/iv_certification_bwa.jpg";
import ImageLogoCoursera from "../../../assets/images/iv_certification_coursera.png";
import ImageLogoPhinconAcademy from "../../../assets/images/iv_company_phincon_academy.jpeg";
import ImageLogoBNSP from "../../../assets/images/iv_certification_bnsp.png";
import ImageLogoLIA from "../../../assets/images/iv_certification_lia.png";
import ImageLogoLPIA from "../../../assets/images/iv_certification_lpia.jpeg";

export const certifications: CertificationType[] = [
  {
    name: "Machine Learning Terapan",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Jul 2022",
    expirationDate: "Jul 2025",
    credentialId: "81P2GK278POY",
    url: "https://www.dicoding.com/certificates/81P2GK278POY",
    skills: [
      "Machine Learning Design",
      "Sentiment Analysis",
      "Computer Vision",
    ],
  },
  {
    name: "Belajar Pengembangan Machine Learning",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Jun 2022",
    expirationDate: "Jun 2025",
    credentialId: "53XE046YYXRN",
    url: "https://www.dicoding.com/certificates/53XE046YYXRN",
    skills: ["Deep Learning", "TensorFlow Development", "Model Deployment"],
  },
  {
    name: "Belajar Machine Learning untuk Pemula",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "May 2022",
    expirationDate: "May 2025",
    credentialId: "0LZ013Q7RP65",
    url: "https://www.dicoding.com/certificates/0LZ013Q7RP65",
    skills: ["Machine Learning", "Data Preprocessing", "Neural Networks"],
  },
  {
    name: "Belajar Dasar Visualisasi Data",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Apr 2022",
    expirationDate: "Apr 2025",
    credentialId: "98XWR6KM9ZM3",
    url: "https://www.dicoding.com/certificates/98XWR6KM9ZM3",
    skills: [
      "Data Visualization",
      "Spreadsheet Analysis",
      "Visual Storytelling",
    ],
  },
  {
    name: "Memulai Pemrograman Dengan C",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Feb 2022",
    expirationDate: "Feb 2025",
    credentialId: "RVZK1QQ3EPD5",
    url: "https://www.dicoding.com/certificates/RVZK1QQ3EPD5",
    skills: ["C (Programming Language)"],
  },
  {
    name: "Memulai Pemrograman Dengan Python",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Feb 2022",
    expirationDate: "Feb 2025",
    credentialId: "GRX5K1L8RZ0M",
    url: "https://www.dicoding.com/certificates/GRX5K1L8RZ0M",
    skills: ["Python (Programming Language)"],
  },
  {
    name: "Belajar Dasar Pemrograman Web",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Jan 2021",
    expirationDate: "Sep 2024",
    credentialId: "07Z653LJMXQR",
    url: "https://www.dicoding.com/certificates/07Z653LJMXQR",
    skills: ["HTML", "Cascading Style Sheets (CSS)", "JavaScript"],
  },
  {
    name: "Aplikasi Perkantoran",
    issuer: "Lembaga Pendidikan Indonesia Amerika",
    logo: ImageLogoLPIA,
    issueDate: "Oct 2020",
    credentialId: "23.20.10.10.00001",
    url: "",
    skills: [
      "Microsoft Word",
      "Microsoft Excel",
      "Presentation Tools",
      "Email Communication",
    ],
  },
  {
    name: "English for Adults : High-Intermediate Levels",
    issuer: "LB LIA English Course",
    logo: ImageLogoLIA,
    issueDate: "Jul 2020",
    credentialId: "00118/EAHL/II/2020/CG",
    url: "",
    skills: ["English Writing", "English Reading"],
  },
  {
    name: "English for Adults : Intermediate Levels",
    issuer: "LB LIA English Course",
    logo: ImageLogoLIA,
    issueDate: "Jul 2018",
    credentialId: "00119/EAIL/II/18/CG",
    url: "",
    skills: ["English Writing", "English Reading"],
  },
  {
    name: "English for Teens : Pre-Intermediate Levels",
    issuer: "LB LIA English Course",
    logo: ImageLogoLIA,
    issueDate: "Mar 2016",
    credentialId: "00721/ETPL/I/16/BN",
    url: "",
    skills: ["English Writing", "English Reading"],
  },
  {
    name: "Pengenalan ke Logika Pemrograman (Programming Logic 101)",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Feb 2023",
    expirationDate: "Feb 2026",
    credentialId: "07Z6GDEVYXQR",
    url: "https://www.dicoding.com/certificates/07Z6GDEVYXQR",
    skills: ["Logic Programming", "Computational Thinking", "Algorithm Design"],
  },
  {
    name: "Memulai Pemrograman Dengan Kotlin",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Feb 2023",
    expirationDate: "Feb 2026",
    credentialId: "2VX3YE7J4PYQ",
    url: "https://www.dicoding.com/certificates/2VX3YE7J4PYQ",
    skills: [
      "Kotlin Fundamentals",
      "Object-Oriented Programming (OOP)",
      "Asynchronous Programming",
    ],
  },
  {
    name: "Memulai Dasar Pemrograman untuk Menjadi Pengembang Software",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Feb 2023",
    expirationDate: "Feb 2026",
    credentialId: "4EXG9OJD1ZRL",
    url: "https://www.dicoding.com/certificates/4EXG9OJD1ZRL",
    skills: [
      "Requirements Analysis",
      "Basic Programming",
      "Software Documentation",
    ],
  },
  {
    name: "Belajar Dasar Git dengan GitHub",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Feb 2023",
    expirationDate: "Feb 2026",
    credentialId: "ERZR0ND5MXYV",
    url: "https://www.dicoding.com/certificates/ERZR0ND5MXYV",
    skills: [
      "Version Control with Git (Commit, Branching, Merging)",
      "Team Collaboration using GitHub (Forking, Pull Requests, Code Review)",
      "Building a Developer Portfolio with GitHub",
    ],
  },
  {
    name: "Belajar Membuat Aplikasi Android untuk Pemula",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Mar 2023",
    expirationDate: "Mar 2026",
    credentialId: "1RXYO86Q1PVM",
    url: "https://www.dicoding.com/certificates/1RXYO86Q1PVM",
    skills: [
      "Android Studio Setup & Application Lifecycle Management",
      "Intent & UI Design using Views, Layouts, and Themes",
      "Building Dynamic Lists with RecyclerView & External Libraries",
    ],
  },
  {
    name: "Belajar Fundamental Aplikasi Android",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Apr 2023",
    expirationDate: "Apr 2026",
    credentialId: "ERZRG5W9OPYV",
    url: "https://www.dicoding.com/certificates/ERZRG5W9OPYV",
    skills: [
      "Android Fundamentals: Activity, Fragment & Navigation",
      "Background Processing, Networking & Local Storage",
      "Modern Android Architecture & Testing Practices",
    ],
  },
  {
    name: "Belajar Prinsip Pemrograman SOLID",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "May 2023",
    expirationDate: "May 2026",
    credentialId: "81P233J4NXOY",
    url: "https://www.dicoding.com/certificates/81P233J4NXOY",
    skills: [
      "Object-Oriented Programming Fundamentals (OOP)",
      "Class Relationships & Software Design Principles",
      "Applying SOLID Principles for Scalable Architecture",
    ],
  },
  {
    name: "Belajar Pengembangan Aplikasi Android Intermediate",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "May 2023",
    expirationDate: "May 2026",
    credentialId: "0LZ0922W0Z65",
    url: "https://www.dicoding.com/certificates/0LZ0922W0Z65",
    skills: [
      "Advanced UI & Animation in Android",
      "Background Services & Location-based Features",
      "Testing, Database, and Firebase Integration",
    ],
  },
  {
    name: "Belajar Membuat Aplikasi Android dengan Jetpack Compose",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "May 2023",
    expirationDate: "May 2026",
    credentialId: "L4PQG1EYQZO1",
    url: "https://www.dicoding.com/certificates/L4PQG1EYQZO1",
    skills: [
      "Declarative UI Development with Jetpack Compose",
      "State Management & Navigation in Compose",
      "UI Testing & Interoperability",
    ],
  },
  {
    name: "Belajar Dasar UX Design",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "May 2023",
    expirationDate: "May 2026",
    credentialId: "4EXGN40DDZRL",
    url: "https://www.dicoding.com/certificates/4EXGN40DDZRL",
    skills: [
      "User Experience Design (UED)",
      "Design Thinking",
      "Wireframing & Prototyping",
      "UX Research",
    ],
  },
  {
    name: "Programming Assistant",
    issuer: "Badan Nasional Sertifikasi Profesi (BNSP)",
    logo: ImageLogoBNSP,
    issueDate: "Dec 2023",
    expirationDate: "",
    credentialId: "62010.2513.0000654.2023",
    url: "",
    skills: [
      "Project Documentation",
      "Object-Oriented Programming (OOP)",
      "UI Design",
      "Android Development",
      "Programming",
      "UI/UX",
    ],
  },
  {
    name: "Cloud Practitioner Essentials (Belajar Dasar AWS Cloud)",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Mar 2024",
    expirationDate: "Mar 2027",
    credentialId: "QLZ94L37MP5D",
    url: "https://www.dicoding.com/certificates/QLZ94L37MP5D",
    skills: [
      "Fundamentals of AWS Cloud & Services",
      "Cloud Infrastructure, Security & Networking",
      "AI, Analytics, and Cost Management on AWS",
    ],
  },
  {
    name: "Preparing Data for Exploration",
    issuer: "Coursera",
    logo: ImageLogoCoursera,
    issueDate: "May 2024",
    expirationDate: "",
    credentialId: "Y8BH4Q23CT9Q",
    url: "https://coursera.org/verify/Y8BH4Q23CT9Q",
    skills: [
      "Spreadsheets",
      "Metadata",
      "Data Ethics",
      "SQL",
      "Data Collection",
    ],
  },
  {
    name: "Basics of Data Analytics: Data, Data Everywhere",
    issuer: "Coursera",
    logo: ImageLogoCoursera,
    issueDate: "May 2024",
    expirationDate: "",
    credentialId: "TEPZ5JL2U7JN",
    url: "https://coursera.org/verify/TEPZ5JL2U7JN",
    skills: [
      "Data Visualization",
      "Data Analytics",
      "Spreadsheets",
      "Data Cleaning",
      "SQL",
    ],
  },
  {
    name: "Ask Questions to Make Data-Driven Decisions",
    issuer: "Coursera",
    logo: ImageLogoCoursera,
    issueDate: "May 2024",
    expirationDate: "",
    credentialId: "YCTHETGKJ8JU",
    url: "https://coursera.org/verify/YCTHETGKJ8JU",
    skills: [
      "Problem Solving",
      "Data Analytics",
      "Spreadsheets",
      "Decision-Making",
    ],
  },
  {
    name: "Processing Data from Raw to Clean",
    issuer: "Coursera",
    logo: ImageLogoCoursera,
    issueDate: "May 2024",
    expirationDate: "",
    credentialId: "WKUQG36CNK8S",
    url: "https://coursera.org/verify/WKUQG36CNK8S",
    skills: [
      "Spreadsheets",
      "Data Cleaning",
      "Sample Size Determination",
      "Data Integrity",
      "SQL",
    ],
  },
  {
    name: "Analyzing Data to Answer Questions",
    issuer: "Coursera",
    logo: ImageLogoCoursera,
    issueDate: "Jun 2024",
    expirationDate: "",
    credentialId: "5PSAGL2F2QGY",
    url: "https://coursera.org/verify/5PSAGL2F2QGY",
    skills: ["Spreadsheets", "Data Analytics", "SQL"],
  },
  {
    name: "Memulai Pemrograman dengan Dart",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Sep 2024",
    expirationDate: "Sep 2027",
    credentialId: "MRZME0N7RPYQ",
    url: "https://www.dicoding.com/certificates/MRZME0N7RPYQ",
    skills: ["Dart", "IntelliJ IDEA"],
  },
  {
    name: "Belajar Dasar AI",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Sep 2024",
    expirationDate: "Sep 2027",
    credentialId: "KEXL15LM0XG2",
    url: "https://www.dicoding.com/certificates/KEXL15LM0XG2",
    skills: ["Artificial Intelligence (AI)", "Machine Learning", "TensorFlow"],
  },
  {
    name: "Android Kotlin Bootcamp",
    issuer: "Phincon Academy",
    logo: ImageLogoPhinconAcademy,
    issueDate: "Sep 2024",
    expirationDate: "",
    credentialId: "10210509240002",
    url: "",
    skills: ["Android Development", "Android Studio", "Kotlin"],
  },
  {
    name: "Belajar Dasar-Dasar DevOps",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Oct 2024",
    expirationDate: "Oct 2027",
    credentialId: "JMZV4338NXN9",
    url: "https://www.dicoding.com/certificates/JMZV4338NXN9",
    skills: ["DevOps Tools", "The Three Ways", "CALMS Framework"],
  },
  {
    name: "Meniti Karier sebagai Software Developer",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Nov 2024",
    expirationDate: "Nov 2027",
    credentialId: "1OP847W12ZQK",
    url: "https://www.dicoding.com/certificates/1OP847W12ZQK",
    skills: [
      "Software Developer Career Path",
      "Developer Mindset",
      "Tech Industry Insights",
    ],
  },
  {
    name: "Memulai Pemrograman Dengan Java",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Nov 2024",
    expirationDate: "Nov 2027",
    credentialId: "98XW58LG4PM3",
    url: "https://www.dicoding.com/certificates/98XW58LG4PM3",
    skills: ["Java", "IntelliJ IDEA", "Object Oriented Programming (OOP)"],
  },
  {
    name: "Belajar Jaringan Komputer untuk Pemula",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Nov 2024",
    expirationDate: "Nov 2027",
    credentialId: "L4PQ5937VZO1",
    url: "https://www.dicoding.com/certificates/L4PQ5937VZO1",
    skills: ["Computer Network", "IP Addressing", "Networking"],
  },
  {
    name: "Belajar Dasar Structured Query Language (SQL)",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Nov 2024",
    expirationDate: "Nov 2027",
    credentialId: "L4PQ5YVN2ZO1",
    url: "https://www.dicoding.com/certificates/L4PQ5YVN2ZO1",
    skills: ["Database Management Systems (DBMS)", "SQL"],
  },
  {
    name: "Belajar Dasar Manajemen Proyek",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Nov 2024",
    expirationDate: "Nov 2027",
    credentialId: "N9ZOYN4M6PG5",
    url: "https://www.dicoding.com/certificates/N9ZOYN4M6PG5",
    skills: ["Project Management"],
  },
  {
    name: "Belajar Dasar Google Cloud",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Nov 2024",
    expirationDate: "Nov 2027",
    credentialId: "1RXY279VQXVM",
    url: "https://www.dicoding.com/certificates/1RXY279VQXVM",
    skills: ["Google Cloud Platform", "Cloud Computing"],
  },
  {
    name: "Belajar Dasar Data Science",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Nov 2024",
    expirationDate: "Nov 2027",
    credentialId: "1OP84R562ZQK",
    url: "https://www.dicoding.com/certificates/1OP84R562ZQK",
    skills: [
      "Fundamental Data Science",
      "Data Analysis & Visualization Tools",
      "Introduction to Machine Learning",
    ],
  },
  {
    name: "React Native Dasar",
    issuer: "BuildWithAngga",
    logo: ImageLogoBWA,
    issueDate: "Dec 2024",
    credentialId: "OOoA9Pcq2k",
    url: "",
    skills: ["React Native", "JavaScript", "Mobile Development"],
  },
  {
    name: "Belajar Membuat Aplikasi Flutter untuk Pemula",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Dec 2024",
    expirationDate: "Dec 2027",
    credentialId: "L4PQ5L2VVZO1",
    url: "https://www.dicoding.com/certificates/L4PQ5L2VVZO1",
    skills: ["Dart", "Flutter", "Mobile Development", "Android Studio"],
  },
  {
    name: "Belajar Back-End Pemula dengan JavaScript",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Dec 2024",
    expirationDate: "Dec 2027",
    credentialId: "1RXY2RKOKXVM",
    url: "https://www.dicoding.com/certificates/1RXY2RKOKXVM",
    skills: [
      "Back-End Development with Node.js",
      "RESTful API Design & Implementation",
    ],
  },
  {
    name: "React Native: Integrasi Dengan REST API (CRUD)",
    issuer: "BuildWithAngga",
    logo: ImageLogoBWA,
    issueDate: "Jan 2025",
    credentialId: "B6HuJ4H9bu",
    url: "",
    skills: ["React Native", "Mobile Development", "Axios"],
  },
  {
    name: "React JavaScript",
    issuer: "BuildWithAngga",
    logo: ImageLogoBWA,
    issueDate: "Jan 2025",
    credentialId: "OLV1y1VUB2",
    url: "",
    skills: ["React.js", "Web Development", "JavaScript"],
  },
  {
    name: "Convert HTML ke React.js Framework",
    issuer: "BuildWithAngga",
    logo: ImageLogoBWA,
    issueDate: "Jan 2025",
    credentialId: "U6abWZP2ay",
    url: "",
    skills: ["React.js", "Web Development", "JavaScript"],
  },
  {
    name: "Complete React Native Beginner to Pro: Bikin Aplikasi Cari Kantor",
    issuer: "BuildWithAngga",
    logo: ImageLogoBWA,
    issueDate: "Feb 2025",
    credentialId: "TgaxSF3Ad8",
    url: "",
    skills: ["React Native", "Mobile Development"],
  },
  {
    name: "Financial Literacy 101",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Jun 2025",
    expirationDate: "Jun 2028",
    credentialId: "EYX4G4LY5ZDL",
    url: "https://www.dicoding.com/certificates/EYX4G4LY5ZDL",
    skills: ["Financial Literacy", "Personal Finance", "Budgeting"],
  },
  {
    name: "Belajar Membuat Front-End Web untuk Pemula",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Jun 2025",
    expirationDate: "Jun 2028",
    credentialId: "MRZMN091KPYQ",
    url: "https://www.dicoding.com/certificates/MRZMN091KPYQ",
    skills: ["JavaScript", "HTML", "CSS"],
  },
  {
    name: "Belajar Dasar Pemrograman JavaScript",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Jun 2025",
    expirationDate: "Jun 2028",
    credentialId: "ERZR29982PYV",
    url: "https://www.dicoding.com/certificates/ERZR29982PYV",
    skills: [
      "JavaScript Programming",
      "Object-Oriented & Functional Programming",
      "Asynchronous JavaScript",
    ],
  },
  {
    name: "Belajar Dasar Cloud dan Gen AI di AWS",
    issuer: "Dicoding Indonesia",
    logo: ImageLogoDicoding,
    issueDate: "Jun 2025",
    expirationDate: "Jun 2028",
    credentialId: "RVZKG946OXD5",
    url: "https://www.dicoding.com/certificates/RVZKG946OXD5",
    skills: ["Cloud", "Gen AI", "AWS"],
  },
];
